<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-35ASNQI8" ignored="0" name="t2" tests="5" failures="3" timestamp="2020-11-15T10:56:52 CST" time="12.103" errors="0">
  <testcase name="test1" time="0.002" classname="com.webtest.testCases.LoginTest"/>
  <testcase name="test2" time="0.0" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.testCases.LoginTest.test2(LoginTest.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.testCases.LoginTest.test3(LoginTest.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="com.webtest.testCases.LoginTest"/>
  <testcase name="test_login" time="6.312" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.webtest.testCases.LoginTest.test_login(LoginTest.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
</testsuite> <!-- t2 -->
